kumuluzee:
  name: Upravljanje s prijavami na termine govorilnih ur
  version: 0.6
  env:
    name: dev
  datasources:
      - jndi-name: jdbc/ConsultationsDS
        connection-url: jdbc:postgresql://localhost:5432/consultations2
        username: postgres
        password: postgres
integrations:
  channels:
    base-url: http://localhost:8081/v1/communication